apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ack-mq-metrics-service
spec:
  ports:
  - name: metricsport
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: controller
  type: NodePort
status:
  loadBalancer: {}
